name: Deploy APK new

on:
  workflow_dispatch:
    inputs:
      build_release_apk:
        type: boolean
        description: "Deploy Release version"
        default: false
        required: false

env:
  INPUT_BUILD_RELEASE_APK: ${{ github.event.inputs.build_release_apk }}

jobs:
  build_and_deploy:
    if: false
    runs-on: ubuntu-latest
    name: Deploy to Firebase App Distribution
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Assemble Release APK
        if: ${{ env.INPUT_BUILD_RELEASE_APK == 'true' }}
        uses: gradle/gradle-build-action@v2
        with:
          arguments: -q assembleRelease
